server:
 port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?serverTimezone=GMT%2B8
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true
    enable-self-preservation: false #禁用自我保护
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  #  instance:
  #    instance-id: payment8001 #主机名称
  #    prefer-ip-address: true

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities